baseurl = "http://themykkanens.com/"
languageCode = "en-US"
title = "The Mykkanens"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"
publishDir =  "docs"

[permalinks]
  post = "/:year/:month/:day/:slug"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
  avatar = "profile.png"
  author = "The Mykkanens"
  description = "Personal website for the Mykkanen family."
  og_image = "/images/family.jpg"
  header-img = ""

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = ""
  Email         = "mr.tyler.mykkanen@gmail.com"
  Twitter       = ""
  LinkedIn      = ""
  Stackoverflow = ""
  Facebook 		= "tyler.mykkanen"

## Main Menu
[[menu.main]]
  name = "ireland"
  weight = 100
  identifier = "ireland"
  url = "/ireland"
[[menu.main]]
  name = "Give"
  weight = 200
  identifier = "Financial Partnership"
  url = "/finances"
[[menu.main]]
    name = "Pray"
    weight = 300
    identifier = "Prayer Support"
    url = "/prayer"
[[menu.main]]
    name = "Trip Log"
    weight = 400
    identifier = "Trip Log"
    url = "/series/ireland-trip-log"
[[menu.main]]
  name = "Colossians Devotional"
  weight = 500
  identifier = "devo"
  url = "/series/colossians-devotional"
